tasks:
  tv_shows_task:
    rss:
      url: http://showrss.info/feeds/all.rss
      other_fields: ['showrss:showname']
    manipulate:
      - series_name:
          from: 'showrss:showname'

    # for additional debug info
    #
    # exec:
    #   on_filter:
    #      for_entries:
    #         - "echo -n {{title}} - {{series_name}}"

    # pull series from here
    include: user_series.yml

    # output to transmission
    transmission:
      host: localhost
      port: 9091
      username: admin
      password: password
