---
# tasks file for ansible/roles/initial-setup
- name: ensure system is up to date
  apt: upgrade=dist
  register: system_upgraded

- name: expand root partition
  command: raspi-config --expand-rootfs
  when: ansible_lsb.id == "Raspbian"

- name: ensure that we have enough power for usb disks (max_usb_current)
  lineinfile:
    dest: /boot/config.txt
    insertbefore: BOF
    line: max_usb_current=1
  when: pi is defined and pi

- name: disable lightdm on boot
  service:
    name: lightdm
    enabled: no

- name: setup new version of nodejs
  shell: curl -sL https://deb.nodesource.com/setup_5.x |  bash -

- name: setup initial needed packages
  apt: pkg="{{ item }}" state=present force=yes
  with_items:
    - python2.7-dev
    - python-setuptools
    - nodejs
    - apt-transport-https
    - usbmount
    - libffi-dev
    - libssl-dev
    - iptables-persistent


- name: ensure kapture group is setup correctly
  group: name=kapture system=yes state=present

- name: ensure sudo group doesnt require password sudo (if xenial)
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo   ALL=(ALL:ALL) ALL$"
    line:    "%sudo   ALL=(ALL:ALL) NOPASSWD: ALL"
  when: ansible_lsb.codename == "xenial"

- name: ensure kapture users are setup correctly
  user:
    groups: sudo,kapture
    name: "{{ kapture_user }}"
    createhome: yes
    home: /var/lib/kapture
    state: present

- name: add public ssh keys
  authorized_key:
    user: "{{ ansible_ssh_user }}"
    state: present
    key: "{{ item }}"
  with_items: "{{ ssh_authorized_keys }}"
  when: pi is defined and pi

- name: change storage path if running via vagrant
  set_fact: storage_block_device=/dev/sdb
  when: vagrant is defined and vagrant

# not the best way to check for this stuff, especially with multiple drives.
# works in the meantime though
# eventually i'd like to use lvm and you add a disk and it'll automatically be added to the lvm layer
- name: get usb disk mount status
  shell: "mountpoint -q {{ storage_path }}0"
  ignore_errors: true
  register: storage_mount_stat

- name: setup disk if needed
  include: setup-disk.yml
  when: storage_mount_stat.rc != 0

- name: restart machine
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true
  when: system_upgraded.changed and pi is defined and pi

- name: waiting for server to come back
  become: false
  connection: local
  wait_for:
    host: "{{ inventory_hostname }}"
    state: started
    port: 22
  when: system_upgraded.changed and pi is defined and pi
